<?php

namespace Diversworld\CalendarEditorBundle\Hooks;

use Contao\PageModel;
use Contao\FrontendUser;
use Contao\System;
use Diversworld\CalendarEditorBundle\Models\CalendarModelEdit;
use Diversworld\CalendarEditorBundle\Services\CheckAuthService;
use Contao\Frontend;
use Psr\Log\LoggerInterface;

class ListAllEventsHook extends Frontend
{
    protected string $strTemplate = '';

    private CheckAuthService $checkAuthService;
    private FrontendUser $user;

    public function __construct(CheckAuthService $checkAuthService, FrontendUser $user)
    {
        parent::__construct();
        $this->checkAuthService = $checkAuthService;
        $this->user = $user;
    }

    public function addEditLinks(array &$event, string $url): void
    {
        $event['editRef'] = $url . '?edit=' . $event['id'];
        $event['editLabel'] = $GLOBALS['TL_LANG']['MSC']['caledit_editLabel'];
        $event['editTitle'] = $GLOBALS['TL_LANG']['MSC']['caledit_editTitle'];
    }

    /**
     * Manipulate the $events array generated by ModuleCalendar and ModuleEventlist.
     */
    public function updateAllEvents(array $events, array $arrCalendars): array
    {
        $this->logger = System::getContainer()->get('monolog.logger.contao.general');

        if (empty($arrCalendars)) {
            return $events;
        }

        $calendarObjects = [];            // Detailed authorization check
        $isUserAdminForCalendar = [];     // Admin status per calendar
        $isUserMemberForCalendar = [];    // Member status per calendar
        $jumpPages = [];                  // Edit links for calendars

        $calendarModels = CalendarModelEdit::findByIds($arrCalendars);
        foreach ($calendarModels as $calendarModel) {
            $currentPid = $calendarModel->id; // Parent-ID for events

            $calendarObjects[$currentPid] = $calendarModel;

            $jumpPages[$currentPid] = '';
            if ($calendarModel->AllowEdit) {
                // Admin and Member status checks
                $isUserAdminForCalendar[$currentPid] = $this->checkAuthService->isUserAdmin($calendarModel, $this->user);
                $isUserMemberForCalendar[$currentPid] = $this->checkAuthService->isUserAuthorized($calendarModel, $this->user);

                // get the jump-to-Edit-page for this calendar
                $page = PageModel::findByPk($calendarModel->caledit_jumpTo);

                if ($page !== null) {
                    $baseUrl = $page->getFrontendUrl();
                    } else {
                    $baseUrl = '';
                    }

                    // Parameter anhängen, z. B. für den Editor-Link
                $jumpPages[$currentPid] = $baseUrl;
            } else {
                // No editing allowed
                $isUserAdminForCalendar[$currentPid] = false;
                $isUserMemberForCalendar[$currentPid] = false;
            }
        }

        $this->logger->info('$event: '.\print_r($events,true) .' - ', ['module' => 'ModuleCalendar']);
        // Process events and add edit links where appropriate
        foreach ($events as &$date) {
            foreach ($date as &$timestamp) {
                foreach ($timestamp as &$event) {
                    $pid = $event['pid'];
                    $this->logger->info('$event: '.\print_r($event,true) .' - ', ['module' => 'ModuleCalendar']);
                    $this->logger->info('jumpPages: '. $jumpPages[$pid]);
                    if (
                        $this->user->id !== null &&
                        $calendarObjects[$pid]->AllowEdit === '1' &&
                        $this->checkAuthService->areEditLinksAllowed(
                            $calendarObjects[$pid],
                            $event,
                            $this->user->id,
                            $isUserAdminForCalendar[$pid],
                            $isUserMemberForCalendar[$pid]
                        )
                    ) {
                        $this->addEditLinks($event, $jumpPages[$pid]);
                    }
                }
            }
        }
        return $events;
    }
}
