services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $projectDir: '%kernel.project_dir%'

  Diversworld\CalendarEditorBundle\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Models,CalendarEditorBundle.php}'

  caledit.service.auth:
    alias: Diversworld\CalendarEditorBundle\Services\CheckAuthService
    public: true

  Diversworld\CalendarEditorBundle\Dca\ModuleDca:
    public: true
